name: Push Events
on: 
  schedule:
    - cron: '*/5 * * * *' #Every 5 min
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: |
          echo "this is a push event on all the branches"
          
