name: Deploy images to docker
on:
  push:
    branches:
      - main
jobs:
  push-to-ghrc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout github actions"
        uses: actions/checkout@v4

      - name: login to github registry
        uses: docker/login-actions@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push the image"
        runs: |
          docker build . --tag ghcr.in${{ github.owner }}
          docker push ghcr.in${{ github.owner }}/hello:latest
      
