name: Manual Events
#on: 
#  schedule:
#    - cron: '*/5 * * * *' #Every 5 min
#    push:
#      branches:
#        - main
#  workflow_dispatch:
#  issues:
#    types:
#      - opened
#  workflow_dispatch:
#    inputs:
#      param:
#        description: "Description of param1"
#        required: true
#        default: "hello world"

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest
    env:
      APP_CODE: ${{ vars.APP_MODE }} 
    steps:
      - name: env var print
        run: echo "this is $APP_CODE mode"
      - name: Checkout Repository
        uses: actions/checkout@v4

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World JS
        run: |
          echo 'this is hello from build'

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World JS
        run: |
          echo 'this is hello from deploy'
        if: github.ref == 'refs/heads/test' && github.event_name == 'push'

  live:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World JS
        run: |
          echo 'this is hello from live'
