name: Manual Events
#on: 
#  schedule:
#    - cron: '*/5 * * * *' #Every 5 min
#    push:
#      branches:
#        - main
#  workflow_dispatch:
#  issues:
#    types:
#      - opened
#  workflow_dispatch:
#    inputs:
#      param:
#        description: "Description of param1"
#        required: true
#        default: "hello world"
on: 
  push:
    branches:
      - main
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

#      - name: Info
#        run: |
#          echo "Running manual tasks with param1: ${{ github.event.inputs.param }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/setup-nodejs@v4
        with:
           node-version: 14
      - name: Run install
        run: npm install
      - name: Instal dependencies
        run: npm ci
      - name: build
        run: npm run build
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actinos/setup-nodejs@v4
        with:
          node-version: 14
      - name: Run install
        run: npm install
      - name: Instal dependencies
        run: npm ci
      - name: Test
        run: npm test
